### ISSUE TITLE
Import Error for fastmp module

### ISSUE THREAD

**Issue by neda-noor-m** [cgraber/NLStruct#3]
Thanks for sharing.
I installed `fastmp` extension using the following commands:
`python setup.py build`
`python setup.py install`
Then, I tried to import `fastmp` in this way:
`from deepstruct.fastmp import fastmp`
Unfortunately, I got this:
```shell
from deepstruct.fastmp import fastmp
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/neda/pycharm-community-2018.1.1/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: /home/neda/Documents/neda/PHD-thesis/code/SPEN/NLStruct_1/deepstruct/fastmp/fastmp.cpython-35m-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num
```

My system has Ubuntu 16.04, and Python 3.5.5. The GCC version is 5.4.

**Comment by neda-noor-m** [comment]
The following is the output of `python setup.py build` on my system. I think that it might be helpful. Everything looks alright although there are lots of Warnings. The files `fastmp.cpython-35m-x86_64-linux-gnu.so` and `fastmpmodule.o` created successfully.

Thanks in advance.

```shell
(SPEN) neda@neda-Lenovo-IdeaPad-Z510:~/Documents/neda/PHD-thesis/code/SPEN/NLStruct_1/deepstruct/fastmp$ python setup.py build
running build
running build_ext
building 'fastmp' extension
gcc -pthread -B /home/neda/anaconda3/envs/SPEN/compiler_compat -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/neda/anaconda3/envs/SPEN/lib/python3.5/site-packages/numpy/core/include -I/home/neda/anaconda3/envs/SPEN/include/python3.5m -c fastmpmodule.cpp -o build/temp.linux-x86_64-3.5/fastmpmodule.o -Wall -W -fopenmp -lgomp -O3 -pedantic -std=c++0x -DWHICH_FUNC=1
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/neda/anaconda3/envs/SPEN/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:0,
                 from /home/neda/anaconda3/envs/SPEN/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/neda/anaconda3/envs/SPEN/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from fastmpmodule.cpp:6:
/home/neda/anaconda3/envs/SPEN/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning is a GCC extension
 #warning "Using deprecated NumPy API, disable it by " \
  ^
/home/neda/anaconda3/envs/SPEN/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
fastmpmodule.cpp:50:64: warning: unused parameter ‘kwds’ [-Wunused-parameter]
 static int FastMP_init(FastMP *self, PyObject *args, PyObject *kwds)
                                                                ^
fastmpmodule.cpp:121:62: warning: unused parameter ‘args’ [-Wunused-parameter]
 static PyObject* fastmp_get_num_msgs(FastMP *self, PyObject *args)
                                                              ^
fastmpmodule.cpp:126:65: warning: unused parameter ‘args’ [-Wunused-parameter]
 static PyObject* fastmp_get_num_beliefs(FastMP *self, PyObject *args)
                                                                 ^
fastmpmodule.cpp:236:61: warning: unused parameter ‘args’ [-Wunused-parameter]
 static PyObject* fastmp_get_beliefs(FastMP* self, PyObject* args)
                                                             ^
fastmpmodule.cpp:241:61: warning: unused parameter ‘args’ [-Wunused-parameter]
 static PyObject* fastmp_get_entropy(FastMP* self, PyObject* args) 
                                                             ^
fastmpmodule.cpp:269:1: warning: missing initializer for member ‘PyMethodDef::ml_meth’ [-Wmissing-field-initializers]
 };
 ^
fastmpmodule.cpp:269:1: warning: missing initializer for member ‘PyMethodDef::ml_flags’ [-Wmissing-field-initializers]
fastmpmodule.cpp:269:1: warning: missing initializer for member ‘PyMethodDef::ml_doc’ [-Wmissing-field-initializers]
fastmpmodule.cpp:310:1: warning: missing initializer for member ‘_typeobject::tp_free’ [-Wmissing-field-initializers]
 };
 ^
fastmpmodule.cpp:310:1: warning: missing initializer for member ‘_typeobject::tp_is_gc’ [-Wmissing-field-initializers]
fastmpmodule.cpp:310:1: warning: missing initializer for member ‘_typeobject::tp_bases’ [-Wmissing-field-initializers]
fastmpmodule.cpp:310:1: warning: missing initializer for member ‘_typeobject::tp_mro’ [-Wmissing-field-initializers]
fastmpmodule.cpp:310:1: warning: missing initializer for member ‘_typeobject::tp_cache’ [-Wmissing-field-initializers]
fastmpmodule.cpp:310:1: warning: missing initializer for member ‘_typeobject::tp_subclasses’ [-Wmissing-field-initializers]
fastmpmodule.cpp:310:1: warning: missing initializer for member ‘_typeobject::tp_weaklist’ [-Wmissing-field-initializers]
fastmpmodule.cpp:310:1: warning: missing initializer for member ‘_typeobject::tp_del’ [-Wmissing-field-initializers]
fastmpmodule.cpp:310:1: warning: missing initializer for member ‘_typeobject::tp_version_tag’ [-Wmissing-field-initializers]
fastmpmodule.cpp:310:1: warning: missing initializer for member ‘_typeobject::tp_finalize’ [-Wmissing-field-initializers]
fastmpmodule.cpp: In function ‘void run_mp(MPGraph<float, int>*, float*, int, float)’:
fastmpmodule.cpp:320:11: warning: unused variable ‘obj_val’ [-Wunused-variable]
     float obj_val = RMPAlgo.RunMP(lambda_msgs, eps, num_iters);
           ^
fastmpmodule.cpp: At global scope:
fastmpmodule.cpp:323:42: warning: unused parameter ‘self’ [-Wunused-parameter]
 static PyObject* fastmpmod_runmp(FastMP* self, PyObject* args)
                                          ^
fastmpmodule.cpp:360:51: warning: unused parameter ‘self’ [-Wunused-parameter]
 static PyObject* fastmpmod_update_beliefs(FastMP* self, PyObject* args)
                                                   ^
In file included from fastmpmodule.cpp:5:0:
Region.h: In instantiation of ‘MPGraph<T, S>::MPGraph() [with T = float; S = int]’:
Region.h:1010:16:   required from here
Region.h:99:9: warning: ‘MPGraph<float, int>::LambdaSize’ will be initialized after [-Wreorder]
  size_t LambdaSize;
         ^
In file included from fastmpmodule.cpp:5:0:
Region.h:56:7: warning:   ‘float MPGraph<float, int>::entropy’ [-Wreorder]
     T entropy;
       ^
In file included from fastmpmodule.cpp:5:0:
Region.h:113:2: warning:   when initialized here [-Wreorder]
  MPGraph() : LambdaSize(0), entropy(0), region_belief_sums(NULL) {};
  ^
Region.h: In instantiation of ‘void MPGraph<T, S>::ComputeLocalFunctionUpdate(T*, int, T, T, bool, MPGraph<T, S>::FunctionUpdateWorkspaceID&) [with T = float; S = int]’:
Region.h:1010:16:   required from here
Region.h:443:86: warning: unused parameter ‘additiveUpdate’ [-Wunused-parameter]
  void ComputeLocalFunctionUpdate(T* lambdaBase, int r, T epsilon, T multiplier, bool additiveUpdate, FunctionUpdateWorkspaceID& w) {
                                                                                      ^
Region.h: In instantiation of ‘size_t MPGraph<T, S>::ComputeBeliefs(T*, T, T*, bool, int) [with T = float; S = int; size_t = long unsigned int]’:
Region.h:1010:16:   required from here
Region.h:891:83: warning: unused parameter ‘num_pair_vals’ [-Wunused-parameter]
  size_t ComputeBeliefs(T* lambdaBase, T epsilon, T* belPtr, bool OnlyUnaries, int num_pair_vals) {
                                                                                   ^
g++ -pthread -shared -L/home/neda/anaconda3/envs/SPEN/lib -B /home/neda/anaconda3/envs/SPEN/compiler_compat -Wl,-rpath=/home/neda/anaconda3/envs/SPEN/lib,--no-as-needed build/temp.linux-x86_64-3.5/fastmpmodule.o -o /home/neda/Documents/neda/PHD-thesis/code/SPEN/NLStruct_1/deepstruct/fastmp/fastmp.cpython-35m-x86_64-linux-gnu.so
```
